# OneOps Proxy Application config
# ===============================

logging:
  level: info

server:
  address: 0.0.0.0
  port: 8080
  compression:
    enabled: true

oneops:
   keywhiz:
       base-url: https://keywhiz:4444/
       svc-user: ${KEYWHIZ_USER:xxxxx}
       svc-password: ${KEYWHIZ_PASS:xxxxx}
       trust-store:
          path: classpath:keystores/keywhiz_truststore.p12
          type: pkcs12
          store-password: changeit
#       key-store:
#          path:
#          type:
#          store-password:
#          key-password:
       cli:
          version: ${KEYWHIZ_CLI_VERSION:1.0.1}
          download-url: https://github.com/oneops/keywhiz-cli/releases/download/${oneops.keywhiz.cli.version}/keywhiz-cli
   ldap:
       server: ldap://ldap.com
       port: 3269
       user-dn: CN=xxxxx,OU=Users,OU=xxxxx,DC=com
       password: ${LDAP_PASS:xxxxx}
       user-base-dn: OU=Users,OU=xxxxx,DC=com
       user-attribute: sAMAccountName
       role-base-dn:
       role-attribute: uniqueMember
       roles[0]:
       trust-store:
           path: classpath:keystores/ldap_truststore.p12
           type: pkcs12
           store-password: changeit


spring:
  jmx:
    enabled: true
    default-domain: oneops
  jackson.serialization:
      INDENT_OUTPUT: true

endpoints:
  beans:
    enabled: false
  env:
    enabled: false

management:
  context-path: /admin

banner:
  location: banner.txt

info:
    name: @project.artifactId@
    description: @project.description@
    version: @project.version@
    keywhiz-cli-version: ${oneops.keywhiz.cli.version}
    keywhiz-cli-url: ${oneops.keywhiz.cli.download-url}
    java: ${java.version}
    java-vendor: ${java.vendor}
    os-name: ${os.name}
    os-arch: ${os.arch}
    os-version: ${os.version}
