# OneOps Proxy Application config
# ===============================
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.jooq.tools: INFO
    com.zaxxer.hikari: INFO

server:
  address: 0.0.0.0
  port: 8443
  compression:
    enabled: true
  session:
    cookie:
      name: SESSION
  ssl:
    enabled: true
    key-store: classpath:keystores/keywhiz_proxy_keystore.p12
    key-store-type: pkcs12
    key-password: kwproxy-password
    key-store-password: kwproxy-password
  use-forward-headers: true

#security:
#  user:
#    role: ADMIN
#    name: oneops
#    password: 0n30ps

oneops:
   keywhiz:
       base-url: https://keywhiz:4444/
       svc-user: ${KEYWHIZ_USER:admin}
       svc-password: ${KEYWHIZ_PASS:xxxxx}
       trust-store:
          path: classpath:keystores/keywhiz_truststore.p12
          type: pkcs12
          store-password: changeit
       #key-store:
          #path:
          #type:
          #store-password:
          #key-password:
       cli:
          version: ${KEYWHIZ_CLI_VERSION:1.0.1}
          download-url: https://github.com/oneops/keywhiz-cli/releases/download/${oneops.keywhiz.cli.version}/keywhiz-cli
   ldap:
       server: ldap://ldap.com
       port: 3269
       user-dn: CN=xxxxx,OU=Users,OU=xxxxx,DC=com
       password: ${LDAP_PASS:xxxxx}
       user-base-dn: OU=Users,OU=xxxxx,DC=com
       user-attribute: sAMAccountName
       role-base-dn:
       role-attribute: uniqueMember
       roles[0]:
       trust-store:
           path: classpath:keystores/ldap_truststore.p12
           type: pkcs12
           store-password: changeit
   auth:
       issuer: OneOps-Proxy
       header: Authorization
       token-type: Bearer
       # HMAC using SHA-512
       signing-key: ${SIGNING_KEY:xxxxxxxxx}
       expires-in-sec: 3600


spring:
  jmx:
    enabled: true
    default-domain: oneops
  jackson.serialization:
      INDENT_OUTPUT: true
  datasource:
    url: ${ONEOPS_DB_URL:jdbc:postgresql://cmsdb.server:5432/kloopzapp}
    username: ${ONEOPS_DB_USER:xxx}
    password: ${ONEOPS_DB_PASS:xxx}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
       maximum-pool-size: 4
       pool-name: keywhiz-proxy
  jooq:
    sql-dialect: postgres

management:
  context-path: /app
  security:
    enabled: false
    roles: ADMIN

banner:
  location: banner.txt

info:
    name: @project.artifactId@
    description: @project.description@
    version: @project.version@
    keywhiz-cli-version: ${oneops.keywhiz.cli.version}
    keywhiz-cli-url: ${oneops.keywhiz.cli.download-url}
    java: ${java.version}
    java-vendor: ${java.vendor}
    os-name: ${os.name}
    os-arch: ${os.arch}
    os-version: ${os.version}